# [tool] 스틱 없는 finger-reach MJCF를 원본 모델에서 재생성.
"""Regenerate the stickless finger-reach MJCF from the pinned upstream model.

``right_reach.xml`` = upstream ``right.xml`` + the same five massless tip sites
``right_with_tip_sites.xml`` declares.  Nothing else: no sticks, no camera, no
testbed.  Keeping this a generator rather than a hand-edited file means the
reach scene cannot silently drift away from the pinned vendor geometry.
"""

from __future__ import annotations

import re
from pathlib import Path

MJCF_DIR = Path(__file__).resolve().parents[1] / "assets/wuji_description/hand/body/mjcf"

# Cosmetic only -- see the note at the call site.  Values mirror the grasp
# scene so both MuJoCo scenes and the Isaac viewport read the same.
VISUAL_BLOCK = """
  <visual>
    <global offwidth="1280" offheight="720" />
    <quality offsamples="4" shadowsize="4096" />
    <headlight ambient="0.34 0.34 0.36" diffuse="0.58 0.58 0.58" specular="0.06 0.06 0.06" />
    <map znear="0.01" zfar="20" />
  </visual>"""

ASSET_BLOCK = """<asset>
    <texture name="reach_sky" type="skybox" builtin="gradient"
             rgb1="0.72 0.80 0.90" rgb2="0.97 0.97 0.98"
             width="512" height="3072" />
    <texture name="reach_floor" type="2d" builtin="checker"
             rgb1="0.70 0.72 0.75" rgb2="0.78 0.80 0.83" width="512" height="512" />
    <material name="reach_floor_mat" texture="reach_floor" texrepeat="18 18"
              specular="0.05" shininess="0.05" reflectance="0.0" />"""

WORLDBODY_LIGHTS = """
    <!-- Visual-only floor pad: contype/conaffinity 0, so it is invisible to
         collision detection and cannot perturb a reach trajectory. -->
    <geom name="reach_floor_visual" type="plane" pos="0 0 -0.12" size="0.6 0.6 0.01"
          material="reach_floor_mat" contype="0" conaffinity="0" group="0" />
    <light name="reach_key" pos="0.35 -0.30 0.60" dir="-0.45 0.40 -0.80"
           diffuse="0.55 0.55 0.55" specular="0.10 0.10 0.10" castshadow="true" />
    <light name="reach_fill" pos="-0.40 0.35 0.45" dir="0.55 -0.45 -0.70"
           diffuse="0.28 0.28 0.30" specular="0.02 0.02 0.02" castshadow="false" />"""
HEADER = """<mujoco model="wujihand-right-reach">
  <!-- Finger-reach diagnostic scene: the official fixed hand and nothing else.
       Derived from the pinned upstream right.xml by inserting the same five
       massless tip sites right_with_tip_sites.xml uses.  Deliberately has NO
       sticks, camera, testbed or ArUco geometry: the reach probe compares joint
       and fingertip trajectories, so any extra dynamic body would inject
       contacts that the Isaac finger_reach scene does not have.
       Generated by tools/build_finger_reach_scene.py -- do not edit by hand. -->"""


def main() -> int:
    base = (MJCF_DIR / "right.xml").read_text(encoding="utf-8")
    scene = (MJCF_DIR / "right_with_tip_sites.xml").read_text(encoding="utf-8")

    sites = re.findall(r"^\s*<site name=\"finger\d_tip\"[^/]*/>\s*$", scene, re.M)
    if len(sites) != 5:
        raise RuntimeError(f"Expected five tip sites in the grasp scene, found {len(sites)}.")

    output = base
    for finger, site in enumerate(sites, start=1):
        pattern = (
            rf"^(\s*)<geom pos=\"[^\"]*\" type=\"mesh\" rgba=\"[^\"]*\" "
            rf"mesh=\"right_finger{finger}_tip_link\" contype=\"1\" conaffinity=\"1\" />\s*$"
        )
        match = re.search(pattern, output, re.M)
        if match is None:
            raise RuntimeError(f"No tip-geom anchor for finger{finger} in the upstream model.")
        output = output[: match.end()] + "\n" + match.group(1) + site.strip() + output[match.end():]

    output = output.replace('<mujoco model="wujihand-right">', HEADER, 1)

    # Match the Isaac viewport's look so the two videos can be compared by eye.
    # The bare MuJoCo default is a dark grey void with one harsh headlight,
    # which makes the same motion read very differently from an Isaac capture.
    # Purely cosmetic: the skybox and lights carry no collision or mass, and the
    # floor pad is contype/conaffinity 0 so it can never touch the hand.
    if "<visual>" not in output:
        output = output.replace("</option>", "</option>" + VISUAL_BLOCK, 1)
        if VISUAL_BLOCK not in output:
            output = re.sub(r"(<option[^>]*/>)", r"\1" + VISUAL_BLOCK, output, count=1)
    output = output.replace("<asset>", ASSET_BLOCK, 1)
    output = output.replace("<worldbody>", "<worldbody>" + WORLDBODY_LIGHTS, 1)
    destination = MJCF_DIR / "right_reach.xml"
    destination.write_text(output, encoding="utf-8")
    print(f"wrote {destination}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
